"""clip-weave pipeline — Intent → Factory → Asset Match → Guard → Delegate.

This is the top-level orchestrator. HF skills handle everything after BRIEF.md
is written and the project directory is assembled; clip-weave does not rebuild
storyboard generation, composition authoring, lint, check, or render.
"""

import logging
import re
from pathlib import Path

from clip_weave.config import Config, load_config
from clip_weave.core.intent_router import route, write_brief
from clip_weave.core.project_factory import setup as factory_setup
from clip_weave.core.delegator import print_delegation_instructions
from clip_weave.adapters.asset_matcher import match_assets
from clip_weave.adapters.rule_guard import scan as guard_scan, save_history

logger = logging.getLogger(__name__)

_FRAME_SPLIT = re.compile(r"(?=^## Frame \d+)", re.MULTILINE)
_SCENE_LINE = re.compile(r"^-\s*scene:\s*(.+)$", re.MULTILINE | re.IGNORECASE)
_CANDIDATE_LINE = re.compile(r"^-\s*asset_candidates:.*$", re.MULTILINE | re.IGNORECASE)


def _inject_asset_candidates(project_dir: Path, cfg: Config | None = None) -> None:
    """Post-HF hook: read STORYBOARD.md, match assets per frame, write back asset_candidates.

    No-op if STORYBOARD.md or asset-descriptions.md is absent.
    Called both on resume (BRIEF.md already exists) and on first run if STORYBOARD.md
    was generated by a previous HF session.
    """
    storyboard_path = project_dir / "STORYBOARD.md"
    desc_file = project_dir / "capture" / "extracted" / "asset-descriptions.md"
    if not storyboard_path.exists() or not desc_file.exists():
        return

    text = storyboard_path.read_text(encoding="utf-8")
    parts = _FRAME_SPLIT.split(text)
    if len(parts) <= 1:
        logger.info("Asset Matcher: no ## Frame sections found in STORYBOARD.md, skipping")
        return

    preamble, frame_texts = parts[0], parts[1:]

    queries = []
    for ft in frame_texts:
        m = _SCENE_LINE.search(ft)
        queries.append(m.group(1).strip() if m else "")

    if not any(queries):
        logger.info("Asset Matcher: no scene: fields found, skipping")
        return

    logger.info("Asset Matcher: matching %d frame scene(s) …", len(queries))
    all_candidates = match_assets(project_dir, queries, cfg=cfg)

    updated_frames = []
    for ft, candidates in zip(frame_texts, all_candidates):
        if not candidates:
            updated_frames.append(ft)
            continue
        candidate_str = "；".join(
            f"{c['filename']} — {c.get('description', '')[:60].strip()}"
            for c in candidates[:3]
        )
        new_line = f"- asset_candidates: {candidate_str}"
        if _CANDIDATE_LINE.search(ft):
            updated = _CANDIDATE_LINE.sub(new_line, ft)
        else:
            updated = ft.rstrip() + f"\n{new_line}\n"
        updated_frames.append(updated)

    storyboard_path.write_text(preamble + "".join(updated_frames), encoding="utf-8")
    logger.info(
        "Asset candidates injected into %d frame(s) in %s",
        len(frame_texts),
        storyboard_path.name,
    )


def run(
    user_input: str,
    project_name: str,
    videos_dir: Path = Path("videos"),
    uploaded_files: list[Path] | None = None,
    message: str = "",
    length: str = "30s",
    cfg: Config | None = None,
) -> Path:
    """Full pipeline: route → init → brief → asset-match → delegate.

    If BRIEF.md already exists in project_dir, the Intent Router and Project
    Factory steps are skipped (§4.1.1 resume path). Returns project_dir.
    """
    if cfg is None:
        cfg = load_config()

    project_dir = videos_dir / project_name

    # §4.1.1 resume path: existing BRIEF.md → inject candidates if STORYBOARD ready, then delegate
    if (project_dir / "BRIEF.md").exists():
        logger.info("BRIEF.md already exists — skipping intent routing, delegating directly")
        _inject_asset_candidates(project_dir, cfg)
        print_delegation_instructions(project_dir)
        return project_dir

    # ① Intent Router
    result = route(user_input, uploaded_files=uploaded_files, message=message, length=length)
    logger.info("Routed to workflow=%s flow=%s source=%s",
                result.workflow, result.flow, result.source_type)

    # ② Project Factory (init + capture)
    factory_setup(project_dir, source_url=result.source_url, uploaded_files=uploaded_files)

    # ③ Write BRIEF.md
    brief_path = write_brief(result, project_dir)
    logger.info("BRIEF.md written: %s", brief_path)

    # ④ Asset Matcher
    desc_file = project_dir / "capture" / "extracted" / "asset-descriptions.md"
    if desc_file.exists():
        if (project_dir / "STORYBOARD.md").exists():
            # STORYBOARD already generated (e.g. re-run after HF session) — inject per-frame
            _inject_asset_candidates(project_dir, cfg)
        else:
            # STORYBOARD not yet generated — log top candidate for early visibility
            logger.info("Running Asset Matcher (pre-storyboard pass) …")
            candidates = match_assets(project_dir, [result.message], cfg=cfg)
            if candidates and candidates[0]:
                logger.info("Top asset candidate: %s", candidates[0][0].get("filename"))

    # ⑤ Delegate to HF workflow
    print_delegation_instructions(project_dir)
    return project_dir


def guard(compositions_dir: Path, project_dir: Path | None = None) -> bool:
    """Run Rule Guard on compositions_dir. Returns True if no violations."""
    result = guard_scan(compositions_dir)
    if result.unknown:
        logger.warning("Rule Guard: %d violation(s) need manual fix:", len(result.unknown))
        for v in result.unknown:
            logger.warning("  [%s] %s:%d — %s", v.rule_id, v.file.name, v.line, v.detail)
    if project_dir:
        save_history(project_dir, result)
    return result.ok
